apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicios
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicios
  strategy:
    type: RollingUpdate
    rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
  template:
    metadata:
      labels:
        app: servicios
        role: servicios
    spec:
      containers:
        - name: servicios
          image: itzelmunguia/servicios:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: servicios

---
apiVersion: v1
kind: Service
metadata:
  name: servicios
  labels:
    app: servicios
spec:
  type: LoadBalancer
  loadBalancerIP: 148.213.1.156
  selector:
   app: servicios
  ports:
   - name: http
     port: 80
     protocol: TCP
     targetPort: 80
  selector:
    role: servicios
